CHANGE MASTER TO
    MASTER_HOST='127.0.0.1',
    MASTER_PORT=3307,
    MASTER_USER='repl',
    MASTER_PASSWORD='wh960903',
    GET_MASTER_PUBLIC_KEY=1,
    MASTER_AUTO_POSITION = 1
    for channel "master_1";
CHANGE REPLICATION FILTER REPLICATE_WILD_DO_TABLE = ('db1.%') FOR CHANNEL "master_1";

CHANGE MASTER TO
    MASTER_HOST='127.0.0.1',
    MASTER_PORT=3308,
    MASTER_USER='repl',
    MASTER_PASSWORD='wh960903',
    GET_MASTER_PUBLIC_KEY=1,
    MASTER_AUTO_POSITION = 1
    for channel "master_2";
CHANGE REPLICATION FILTER REPLICATE_WILD_DO_TABLE = ('db2.%') FOR CHANNEL "master_2";

START SLAVE FOR CHANNEL "master_1";
START SLAVE FOR CHANNEL "master_2";

SHOW SLAVE STATUS FOR CHANNEL "master_1";
SHOW SLAVE STATUS FOR CHANNEL "master_2";

SELECT * FROM replication_connection_status;